### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by Poikilos** [tjwill95/voronizer#1]
I'm not sure if you know, but having no license is legally considered as "[no permission](https://choosealicense.com/no-permission/)," which is the most restrictive way to publish your code. If you make a new file and name it LICENSE, GitHub will give you a nice interface to choose a license. I'd like a GPL compatible license (v3 preferably) so I can use this in my Skeinforge (early 3D printing software) [fork](https://github.com/poikilos/skeinforge).

**Comment by tjwill95** [comment]
I was not aware of that, my apologies!  First time I've really used Github for anything.  Working on adding a license now, I wish you the best of luck with your own projects!

**Comment by Poikilos** [comment]
Thanks!
